name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  # Lightweight test before publishing (single version)
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Quick test with Odoo 16.0 (stable version)
      run: |
        echo "🚀 Starting lightweight test with Odoo 16.0..."
        
        # Start only essential services
        docker compose up -d postgres wkhtml
        
        # Wait for PostgreSQL
        timeout 60 bash -c "until docker compose exec postgres pg_isready -U postgres >/dev/null 2>&1; do sleep 2; done"
        
        # Setup user and database
        docker compose exec postgres psql -U postgres -c "CREATE USER odoo WITH CREATEDB PASSWORD 'odoo';" || true
        docker compose exec postgres createdb -U postgres -O odoo odoo16 || true
        
        # Quick Odoo initialization
        timeout 240 docker compose run --rm odoo16 odoo \
          --database=odoo16 \
          --db_user=odoo \
          --db_password=odoo \
          --db_host=postgres \
          --init=base \
          --stop-after-init \
          --without-demo=all
        
        # Start Odoo
        docker compose up -d odoo16
        
        # Wait for service
        timeout 120 bash -c "until curl -sf http://localhost:16069/web/database/selector >/dev/null; do sleep 3; done"
        
        # Run tests
        ODOO_DB="odoo16" \
        ODOO_USER="admin" \
        ODOO_PW="admin" \
        ODOO_BASE_URL="http://localhost:16069" \
        timeout 300 npm test

    - name: Cleanup
      if: always()
      run: docker compose down --volumes --remove-orphans || true

  publish:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GHT }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          - Enhanced security validations
          - Multi-version Odoo support (12.0-19.0)
          - Comprehensive test suite (37 tests)
          - Docker environment for development
          
          ## Supported Odoo Versions
          - ✅ Odoo 12.0
          - ✅ Odoo 13.0
          - ✅ Odoo 14.0
          - ✅ Odoo 15.0
          - ✅ Odoo 16.0
          - ✅ Odoo 17.0
          - ✅ Odoo 18.0
          - ✅ Odoo 19.0
        draft: false
        prerelease: false
